// SPDX-FileCopyrightText: 2026 Tobias Hoelzer (omp port)
// SPDX-License-Identifier: AGPL-3.0-only


// Pure post-processing of the generated sections JSON, applied after the
// per-section model calls and before render. Two independent passes:
//
// - dedupeIncidents (C12): sections are generated by separate model calls
//   (buildSectionPrompts), so the same incident can be written up in
//   friction_analysis, suggestions and (if the model drifts) elsewhere, with
//   no shared id to recognise the repeat. The only trustworthy cross-section
//   key is the evidence_sessions array itself (code-assigned, B10), never an
//   id the model invents. The first section to claim a session id (in
//   precedence order) keeps the full item; any later item sharing that id is
//   collapsed to a one-line reference.
// - dedupeRecommendations: a second, independent key for the four
//   suggestions arrays — a normalized title (plus `where` for
//   config_additions) — because the same recommendation can be phrased
//   twice across categories (e.g. both a config_additions and a
//   features_to_try entry) even when their evidence_sessions don't fully
//   overlap.
//
// enforceBudget (C13) is a separate pass: per-field word budgets, with one
// model-call retry (injected, so this stays pure/testable) and a
// sentence-boundary truncation fallback.

import type { SuggestionSections } from "./prompts.ts";

type AnyRecord = Record<string, unknown>;



// ─── C12: incident dedupe ──────────────────────────────────────────────────

/** Precedence order: first source to claim an evidence session id wins the full write-up. */
const INCIDENT_SOURCES: Array<{ section: string; arrayField: string; textField: string; clearFields?: string[] }> = [
	{ section: "friction_analysis", arrayField: "ongoing", textField: "description", clearFields: ["examples"] },
	{ section: "suggestions", arrayField: "stop_doing", textField: "why" },
	{ section: "suggestions", arrayField: "config_additions", textField: "why" },
	{ section: "suggestions", arrayField: "features_to_try", textField: "why_for_you" },
	{ section: "suggestions", arrayField: "usage_patterns", textField: "detail" },
];

const SECTION_LABELS: Record<string, string> = {
	friction_analysis: "Friction",
	suggestions: "Next Steps",
	on_the_horizon: "Future Workflows",
	interaction_style: "How You Work",
};

/**
 * Collapses an incident to a single owning section. Two items are the same
 * incident if they share at least one evidence_sessions id; the earliest
 * (by INCIDENT_SOURCES precedence) keeps its full text, later ones are
 * replaced with a short "see X" reference so the item still renders (its
 * other required fields are untouched) without repeating the write-up.
 */
export function dedupeIncidents(sections: AnyRecord): AnyRecord {
	const result = structuredClone(sections) as AnyRecord;
	const claimedBy = new Map<string, string>(); // evidence session id -> owning section label

	for (const source of INCIDENT_SOURCES) {
		const container = result[source.section] as AnyRecord | undefined;
		const items = container && Array.isArray(container[source.arrayField]) ? (container[source.arrayField] as AnyRecord[]) : [];
		for (const item of items) {
			const evidence = Array.isArray(item.evidence_sessions) ? (item.evidence_sessions as string[]) : [];
			if (!evidence.length) continue;
			const owner = evidence.map((id) => claimedBy.get(id)).find((label): label is string => Boolean(label));
			if (owner) {
				item[source.textField] = `See ${owner} for details.`;
				for (const field of source.clearFields ?? []) {
					if (Array.isArray(item[field])) item[field] = [];
				}
				continue;
			}
			const label = SECTION_LABELS[source.section] ?? source.section;
			for (const id of evidence) if (!claimedBy.has(id)) claimedBy.set(id, label);
		}
	}
	return result;
}

// ─── Recommendation dedupe (title/config-key, not evidence) ────────────────

/** The primary key is the normalized title text (addition/feature/title/what),
 * so the same recommendation phrased in a different category (e.g. both a
 * config_additions and a features_to_try entry) still collapses; `where`
 * (the config file/location) is only a fallback for items with no title text. */
function recommendationKey(item: AnyRecord): string {
	const title = typeof item.addition === "string" ? item.addition
		: typeof item.feature === "string" ? item.feature
		: typeof item.title === "string" ? item.title
		: typeof item.what === "string" ? item.what
		: typeof item.where === "string" ? item.where
		: "";
	return title.toLowerCase().replace(/[^a-z0-9]+/g, " ").trim();
}

/**
 * Drops a later suggestion item whose normalized title matches one already
 * kept, across all four arrays combined. Independent of dedupeIncidents:
 * this catches the same recommendation restated in a different category,
 * which evidence-session overlap alone would not.
 */
export function dedupeRecommendations(suggestions: SuggestionSections): SuggestionSections {
	const seen = new Set<string>();
	const dedupe = <T extends AnyRecord>(items?: T[]): T[] | undefined => {
		if (!items) return items;
		return items.filter((item) => {
			const key = recommendationKey(item);
			if (!key || seen.has(key)) return false;
			seen.add(key);
			return true;
		});
	};
	return {
		config_additions: dedupe(suggestions.config_additions as AnyRecord[] | undefined) as SuggestionSections["config_additions"],
		features_to_try: dedupe(suggestions.features_to_try as AnyRecord[] | undefined) as SuggestionSections["features_to_try"],
		usage_patterns: dedupe(suggestions.usage_patterns as AnyRecord[] | undefined) as SuggestionSections["usage_patterns"],
		stop_doing: dedupe(suggestions.stop_doing as AnyRecord[] | undefined) as SuggestionSections["stop_doing"],
	};
}

// ─── C13: word budgets ──────────────────────────────────────────────────────

export function wordCount(text: string): number {
	const trimmed = text.trim();
	return trimmed ? trimmed.split(/\s+/).length : 0;
}

// Why: split only where terminal punctuation is followed by whitespace. A
// global match() silently skips text it cannot match, so a period inside a
// number ("$18.51") used to drop everything before it.
function splitSentences(text: string): string[] {
	const parts = text.trim().split(/(?<=[.!?])\s+/);
	return parts.map((s) => s.trim()).filter(Boolean);
}

/** Truncates to the longest prefix of whole sentences that fits maxWords; a
 * single sentence already over budget is hard-truncated to maxWords words. */
export function truncateAtSentence(text: string, maxWords: number): string {
	const sentences = splitSentences(text);
	let result = "";
	let words = 0;
	for (const sentence of sentences) {
		const w = wordCount(sentence);
		if (words + w > maxWords) break;
		result = result ? `${result} ${sentence}` : sentence;
		words += w;
	}
	if (result) return result;
	return `${text.trim().split(/\s+/).slice(0, maxWords).join(" ")}\u2026`;
}

/** Hard-truncates at a word boundary with no ellipsis; used for short labels
 * (e.g. `*.title`) where an appended "..." would blow the word budget back
 * over the cap it exists to enforce. */
export function truncateAtWord(text: string, maxWords: number): string {
	return text.trim().split(/\s+/).slice(0, maxWords).join(" ");
}

export type BudgetTarget = { section: string; arrayField?: string; field: string; maxWords: number; noEllipsis?: boolean };

// Why 40 words: C13's summary-card budget. Workflow descriptions (what_works)
// get the same numeric cap rather than a separate "2 sentences" code path —
// two real sentences of prose are rarely longer than 40 words, and a single
// word-count budget keeps enforceBudget's contract uniform.
export const DEFAULT_WORD_BUDGETS: BudgetTarget[] = [
	{ section: "friction_analysis", arrayField: "ongoing", field: "description", maxWords: 40 },
	{ section: "what_works", arrayField: "impressive_workflows", field: "description", maxWords: 40 },
	{ section: "suggestions", arrayField: "stop_doing", field: "why", maxWords: 40 },
	{ section: "suggestions", arrayField: "config_additions", field: "why", maxWords: 40 },
	{ section: "suggestions", arrayField: "features_to_try", field: "why_for_you", maxWords: 40 },
	{ section: "suggestions", arrayField: "usage_patterns", field: "detail", maxWords: 40 },
	{ section: "on_the_horizon", arrayField: "opportunities", field: "whats_possible", maxWords: 40 },
	// C2: interaction_style's blocks shape (not the legacy narrative shape).
	{ section: "interaction_style", arrayField: "blocks", field: "body", maxWords: 60 },
	{ section: "interaction_style", field: "key_pattern", maxWords: 30 },
	{ section: "suggestions", arrayField: "config_additions", field: "title", maxWords: 10, noEllipsis: true },
	{ section: "suggestions", arrayField: "features_to_try", field: "title", maxWords: 10, noEllipsis: true },
	{ section: "suggestions", arrayField: "usage_patterns", field: "title", maxWords: 10, noEllipsis: true },
	{ section: "suggestions", arrayField: "stop_doing", field: "title", maxWords: 10, noEllipsis: true },
	{ section: "friction_analysis", arrayField: "ongoing", field: "title", maxWords: 10, noEllipsis: true },
];
/**
 * Over-budget fields get exactly one retry through the injected `retry`
 * (the real caller wires this to a model call asking for a shorter
 * rewrite); if the retry is still over budget, truncate at a sentence
 * boundary rather than loop. `retry` defaults to identity so tests and
 * --no-llm runs can call this without a model.
 */
export async function enforceBudget(
	sections: AnyRecord,
	budgets: BudgetTarget[],
	retry: (text: string, target: BudgetTarget) => Promise<string> = async (text) => text,
): Promise<AnyRecord> {
	const result = structuredClone(sections) as AnyRecord;
	for (const target of budgets) {
		const container = target.arrayField ? ((result[target.section] as AnyRecord | undefined)?.[target.arrayField]) : result[target.section];
		const items = target.arrayField ? (Array.isArray(container) ? (container as AnyRecord[]) : []) : container ? [result[target.section] as AnyRecord] : [];
		for (const item of items) {
			const text = item[target.field];
			if (typeof text !== "string" || wordCount(text) <= target.maxWords) continue;
			let candidate = await retry(text, target);
			if (wordCount(candidate) > target.maxWords) candidate = target.noEllipsis ? truncateAtWord(candidate, target.maxWords) : truncateAtSentence(candidate, target.maxWords);
			item[target.field] = candidate;
		}
	}
	return result;
}
